test: fix test causing build issue
test_tpm2_auth_util.c:188:16: error: ‘auth_handle’ is used
uninitialized in this function [-Werror=uninitialized]

Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>